/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.vsu.cs.course2.a1pha.linear_algebra;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
